name: DevSecOps-Security-Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. SAST (Static Code)
      - name: Snyk Code Scan
        uses: snyk/actions/node@master
        continue-on-error: true  # <--- Add this
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test

      # 2. SCA (Dependencies)
      - name: Snyk Open Source Scan
        uses: snyk/actions/node@master
        continue-on-error: true  # <--- Add this
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      # 3. IaC (Dockerfile)
      - name: Snyk Infrastructure Scan
        uses: snyk/actions/node@master
        continue-on-error: true  # <--- Add this
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: iac test Dockerfile