name: DevSecOps-Security-Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. SCAN FOR CODE VULNERABILITIES (SAST)
      - name: Snyk Code Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test

      # 2. SCAN FOR VULNERABLE LIBRARIES (SCA)
      - name: Snyk Open Source Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      # 3. SCAN FOR INFRASTRUCTURE ERRORS (IaC)
      - name: Snyk Infrastructure Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: iac test Dockerfile